task_1_1_1
vlasival/OOP pull request #11
Opened 2023-09-19 14:45 UTC by vlasival

2023-09-19 17:50 UTC, galinabykova requested changes

2023-09-19 17:50 UTC, galinabykova commented on task_1_1_1/app/src/main/java/task/App.java
> +        int left = 2 * i + 1; // Левый дочерний элемент
вместо комментария можно назвать переменную leftChildElement. Комментарии должны дополнять код, чтобы в нём можно было легче разобраться, но, если что-то можно выразить средствами языка, это лучше выражать средствами языка

2023-09-19 17:50 UTC, galinabykova commented on task_1_1_1/app/src/main/java/task/App.java
> +            heapify(arr, n, largest);
могут ли тут возникнуть проблемы из-за рекурсии?

2023-09-19 17:50 UTC, galinabykova commented on task_1_1_1/.DS_Store
что это за файлик? нужно ли добавлять его в гит?

2023-09-20 03:36 UTC, vlasival commented on task_1_1_1/app/src/main/java/task/App.java
> +            heapify(arr, n, largest);
Могут возникнуть проблемы при слишком глубокой рекурсии на очень больших массивах. В таком случае стек переполнится и вылезет ошибка stackoverflow. Рекурсия имеет ограничивающее условие, при которой она останавливается. Условие возникает либо когда дочерний элемент за границей массива, либо когда наибольший элемент уже лежит в корне дерева (или поддерева)

2023-09-20 03:37 UTC, galinabykova requested changes
для очной защиты тебе надо будет запустить программу, которая демонстрирует работу твоей функции, так что напиши ещё main

2023-09-20 11:15 UTC, galinabykova requested changes
исправь ещё замечания от reviewdog...

2023-09-21 02:09 UTC, galinabykova approved these changes

2023-09-21 02:26 UTC, merged