task_1_1_2
vlasival/OOP pull request #12
Opened 2023-09-27 17:41 UTC by vlasival

2023-09-27 18:26 UTC, vlasival commented
Buenas noches!

2023-09-27 18:31 UTC, galinabykova requested changes

2023-09-27 18:31 UTC, galinabykova commented on task_1_1_2/app/src/main/java/task/Polynomial.java
> +    public boolean equals(Polynomial poly) {
здесь неверный входной параметр. Чтобы проверить, что ты действительно переопределяешь метод, используй override

2023-09-27 18:31 UTC, galinabykova commented on task_1_1_2/app/src/main/java/task/Polynomial.java
> +    public boolean equals(Polynomial poly) {
с equals нужно переопределять hashcode
https://javarush.com/groups/posts/3957-kofe-breyk-168-zachem-pereopredeljatjh-metodih-equals-i-hashcode-v-java

2023-09-27 18:31 UTC, galinabykova commented on task_1_1_2/app/src/test/java/task/AppTest.java
сделай больше тестов, хотя бы по парочке на каждую операцию, какие-нибудь краевые случаи, ещё что-то

2023-09-27 18:31 UTC, galinabykova commented on task_1_1_2/app/src/test/java/task/AppTest.java
> +        assertEquals("-2x^3 + 2", result.toString());
сравнивай не строчки, а полиномы

2023-10-02 17:46 UTC, galinabykova requested changes

2023-10-02 17:46 UTC, galinabykova commented on task_1_1_1/app/bin/main/task/App.class
кажется, ты случайно добавил эти файлики, нужно убрать

2023-10-02 17:46 UTC, galinabykova commented on task_1_1_2/app/bin/main/task/Main.class
файлы с расширением .class не нужно добавлять в репозиторий

2023-10-02 17:46 UTC, galinabykova commented on task_1_1_2/app/src/test/java/task/AppTest.java
> +class AppTest {
лучше дать этому классу более осмысленное название

2023-10-02 17:46 UTC, galinabykova commented on task_1_1_2/app/src/test/java/task/AppTest.java
> +        assertTrue(p1.equals(p2));
лучше использовать assertEquals, потому что он напечатает более красивый вывод в случае ошибки. После того, как ты переопределил equals, оно должно завестись

2023-10-02 17:46 UTC, galinabykova commented on task_1_1_2/app/src/test/java/task/AppTest.java
> +    public void testMain() {
в этой задаче нужно пройти порог без этого теста. Можешь перенести точку входа (main) в Polynomial, чтобы не было красного в отчёте jacoco

2023-10-03 02:44 UTC, vlasival commented on task_1_1_1/app/bin/main/task/App.class
Да, действительно не заметил, как VS код мне подсунул эти бинарники)

2023-10-03 03:06 UTC, vlasival commented
Исправления:
- Все assertTrue/assertFalse заменены assertEquals/assertNotEquals
- AppTest теперь имеет название TestPolynomialMethods
- Бинарные файлы и дополнительные файлы IDE больше не загружаются на гитхаб

Вопрос: Нужно ли в .gitignore записывать файлы конфигурации git (такие как gitignore и gitattributes)?

2023-10-03 03:27 UTC, galinabykova requested changes

2023-10-03 03:27 UTC, galinabykova commented on task_1_1_2/app/src/test/java/task/TestPolynomialMethods.java
> +class TestPolynomialMethods {
вам нужно придерживаться Google Java Style 
https://google.github.io/styleguide/javaguide.html
В пункте 5.2.2 написано "A test class has a name that ends with Test, for example, HashIntegrationTest."

2023-10-03 03:27 UTC, galinabykova commented on task_1_1_2/app/build.gradle
> +    mainClass = 'task_1_1_2.App'
кажется, этого класса уже нет

2023-10-03 04:08 UTC, galinabykova commented
> gitattributes
Мне кажется, обычно их не добавляют в gitignore, но можно придумать какие-то ситуации, когда это может быть полезно. Если же у тебя какой-то особенные .gitignore, который делает что-то неожиданное для других разработчиков, наверно не надо (хотя я себе плохо представляю такую ситуацию). Если ты блокируешь всю папку .idea, то и .gitignore в ней кажется уже не нужным ни локально, ни на гитхабе.

2023-10-03 04:11 UTC, galinabykova approved these changes

2023-10-03 05:58 UTC, merged