task_1_3_1
vlasival/OOP pull request #16
Opened 2023-11-08 18:11 UTC by vlasival

2023-11-08 19:29 UTC, galinabykova requested changes

2023-11-08 19:29 UTC, galinabykova commented on task_1_3_1/app/src/main/java/task/SubstringSearch.java
> +    @ExcludeFromJacocoGeneratedReport
почему тут так?

2023-11-08 19:29 UTC, galinabykova commented on task_1_3_1/app/src/main/java/task/SubstringSearch.java
> +    @ExcludeFromJacocoGeneratedReport
почему эта функция не должна учитываться?

2023-11-08 19:29 UTC, galinabykova commented on task_1_3_1/app/src/test/java/task/SubstringSearchTest.java
> +    // @Test
нужно будет сделать большой файлик)

2023-11-12 11:46 UTC, galinabykova requested changes

2023-11-12 11:46 UTC, galinabykova commented on task_1_3_1/app/src/test/java/task/SubstringSearchTest.java
> +        assertEquals(expected.toString(), res);
почему ты решил сравнивать строчки здесь?

2023-11-12 11:46 UTC, galinabykova commented on task_1_3_1/app/src/test/java/task/SubstringSearchTest.java
> +        long fileSize = 1024L * 1024 * 1024 * 8; // 16 gb will be in total
судя по коду дальше, это половина размера файла. Мне кажется, лучше назвать её соответствующе, чтобы не путало

2023-11-12 11:46 UTC, galinabykova commented on task_1_3_1/app/src/main/java/task/SubstringSearch.java
> +                indices.add((long) (textIndex - patternIndex));
почему здесь int преобразуется в long? Не очень поняла, почему textIndex int, а в indices long, объясни, пожалуйста

2023-11-12 11:46 UTC, galinabykova commented on task_1_3_1/app/src/main/java/task/SubstringSearch.java
> +            System.err.println("Error!");
здесь ты подавляешь ошибку, сообщая о ней в stderr. Может ли пользователь твоей функции как-то понять из кода, произошла ошибка или нет?

2023-11-12 13:48 UTC, vlasival commented on task_1_3_1/app/src/test/java/task/SubstringSearchTest.java
> +        assertEquals(expected.toString(), res);
Изначально не было теста на функцию, которая печатает массив индексов в приемлемом виде, поэтому я решил делать тест на две функции сразу, но потом вспомнил, что это неправильно и сделал отдельный тест. А исправить этот забыл, сейчас исправлю

2023-11-12 14:03 UTC, vlasival commented on task_1_3_1/app/src/main/java/task/SubstringSearch.java
> +                indices.add((long) (textIndex - patternIndex));
Вообще вы правы, нет смысла в методе findSubstring хранить список long-ов, так как индексы не могут превышать размер одного чанка (в моём случае он указан в методе findSubstringIndices и равен 10Мб), на котором мы ищем подстроку. То есть достаточно из этого метода доставать индексы подстроки в виде списка int-ов, а уже позже, в главном методе findSubstringIndices добавлять эти индексы в список long-ов, так как уже в нём индексы могут превышать int

2023-11-12 14:09 UTC, vlasival commented on task_1_3_1/app/src/main/java/task/SubstringSearch.java
> +            System.err.println("Error!");
Ну да, функция говорит "Ошибка!" в stderr, если не удалось открыть файл. А также печатается printStackTrace ошибки. На самом деле конкретно эта строчка осталась после моего ручного дебаггинга, но свою функцию выполнять должна)

2023-11-13 04:43 UTC, galinabykova approved these changes

2023-11-13 06:10 UTC, merged