task_1_5_1
vlasival/OOP pull request #18
Opened 2023-12-06 16:39 UTC by vlasival

2023-12-06 20:14 UTC, galinabykova requested changes

2023-12-08 01:49 UTC, AntonTsoy requested changes

2023-12-08 01:49 UTC, AntonTsoy commented on task_1_5_1/app/src/main/java/task/Calculator.java
> +    private static boolean isOperator(String elem) {
По правилам хорошего тона в классах приватные методы объявляются раньше публичных

2023-12-08 01:49 UTC, AntonTsoy commented on task_1_5_1/app/src/main/java/task/Calculator.java
> +    public static double calculate(String in) {
Переменной входной строки можно дать более осмысленное и полное имя. Её можно спутать с System.in

2023-12-08 01:53 UTC, vlasival commented on task_1_5_1/app/src/main/java/task/Calculator.java
> +    private static boolean isOperator(String elem) {
Ээээээааааааыыыыыыээээъъъъъъъъъййййййй

2023-12-08 01:54 UTC, vlasival commented on task_1_5_1/app/src/main/java/task/Calculator.java
> +    public static double calculate(String in) {
Никнейм можно сделать на гихабе более осмысленным, а не просто фамилия имя

2023-12-12 02:42 UTC, AntonTsoy approved these changes
Отлично, молодец, продолжай в том же духе

2023-12-13 10:55 UTC, vlasival commented on task_1_5_1/app/src/main/java/task/operations/Pow.java
> +        if (op1 < 0.000000001) {
Тут op1 это основание степени. Отрицательное основание в любой степени, кроме целой, это число не действительное, мнимое (а может и не мнимое, может что-то ещё посложнее). Можно было бы конечно проверить double на близость к целому числу, но double он всё равно имеет только 64 битную точность.

2023-12-13 11:10 UTC, galinabykova requested changes

2023-12-13 11:10 UTC, galinabykova commented on task_1_5_1/app/src/main/java/task/operations/OprationFactory.java
> +public class OprationFactory {
о, тут опечатка, кажется

2023-12-13 11:10 UTC, galinabykova commented on task_1_5_1/app/src/main/java/task/CalculationException.java
нужна иерархия исключений) не одно исключение

2023-12-13 11:10 UTC, galinabykova commented on task_1_5_1/app/src/main/java/task/operations/OprationFactory.java
почему ты решил фабрику закинуть в этот пакет?

2023-12-13 16:47 UTC, galinabykova approved these changes

2023-12-14 01:31 UTC, AntonTsoy requested changes

2023-12-14 01:31 UTC, AntonTsoy commented on task_1_5_1/app/src/main/java/task/Calculator.java
> +package task;
Дай более осмысленное имя пакету. У тебя у всех лаб одни те же названия пакетов, хотя задачи ты делаешь на разные темы

2023-12-14 01:31 UTC, AntonTsoy commented on task_1_5_1/app/src/main/java/task/Factory/OperationFactory.java
> +package task.factory;
Почему ты решил перенести фабрику в отдельный пакет?

2023-12-14 01:31 UTC, AntonTsoy commented on task_1_5_1/app/src/main/java/task/operations/Pow.java
> +        double op1;
Плохой нейминг

2023-12-14 01:31 UTC, AntonTsoy commented on task_1_5_1/app/src/test/java/task/CalculatorTest.java
> +        assertEquals(0, Calculator.calculate("- sqrt 32 pow * 8 4 0.5"));
По условию задачи пользователь должен вводить выражения в префиксном виде. Твой калькулятор обработал выражение, котором знаки перемешаны с числами, без исключений. Это недопустимо!

2023-12-15 13:12 UTC, merged