task_1_2_2
vlasival/OOP pull request #20
Opened 2023-12-24 18:47 UTC by vlasival

2023-12-25 05:13 UTC, galinabykova requested changes

2023-12-25 05:13 UTC, galinabykova commented on task_1_2_2/app/src/main/java/task/resources/ReaderMatrix.java
в resources код не стоит добавлять. Эту папку обычно используют для ресурсов, и никто не ожидает, что тут будет код

2023-12-25 05:13 UTC, galinabykova commented on task_1_2_2/app/src/main/java/task/resources/ReaderMatrix.java
> +        } catch (IOException e) {
тут съедается ошибка о произошедшей ошибке. При таком использовании лучше использовать конструктор 
https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html#Exception-java.lang.String-java.lang.Throwable-
в своём исключении

2023-12-25 05:13 UTC, galinabykova commented on task_1_2_2/app/src/test/java/task/GraphTest.java
мне кажется, стоит разделить этот файл хотя бы на парочку: тестирование конкретных представлений графов, тестирование модели графа

2023-12-25 05:13 UTC, galinabykova commented on task_1_2_2/app/src/test/java/task/GraphTest.java
может быть стоит отдельно протестировать сортировку на каком-нибудь замоканном представлении графа (это не обязательно)

2023-12-27 04:06 UTC, vlasival commented on task_1_2_2/app/src/main/java/task/graphModel/Graph.java
> +    Vertex<V> addVertex(V data);
Graph - это интерфейс  и у него по умолчанию стоит модификатор доступа public, а также он abstract

2023-12-27 04:13 UTC, galinabykova commented on task_1_2_2/app/src/main/java/task/graphModel/Graph.java
> +    Vertex<V> addVertex(V data);
О, хорошо

2023-12-27 04:26 UTC, galinabykova requested changes
reviewdog

2023-12-27 04:43 UTC, galinabykova approved these changes

2023-12-27 04:43 UTC, merged