task_2_2_1
vlasival/OOP pull request #23
Opened 2024-04-09 11:04 UTC by vlasival

2024-04-09 15:38 UTC, galinabykova requested changes
Хорошее решение, мне понравилась твоя архитектура) на мягкий - пройди порог по покрытию, остальные замечания на жёсткий

2024-04-09 15:38 UTC, galinabykova commented on task_2_2_1/app/src/main/java/org/pizzeria/customQueue/IBlockingQueue.java
Вау, ты даже интерфейс сделал, мощно

2024-04-09 15:38 UTC, galinabykova commented on task_2_2_1/app/src/main/java/org/pizzeria/Pizzeria.java
> +    public void addOrder(int count) throws InterruptedException {
в этом классе нужно сделать метод для добавления заказа и добавить тесты, в которых заказы появляются не все сразу. Например, можно сделать тест, в котором сначала выполняются заказы, мы ждём время, гарантированное, чтобы очередь опустела и затем добавляем ещё один заказ. Это нужно, потому что без этого многие случаи, которые должны обрабатываться твоей пиццерией, не отработают и мы может быть случайно не заметим ошибку

2024-04-09 15:38 UTC, galinabykova commented on task_2_2_1/app/src/main/java/org/pizzeria/worker/courier/Courier.java
> +    public void run() {
кажется, тут сейчас никак не используется вместительность рюкзака

2024-04-09 15:38 UTC, galinabykova commented on task_2_2_1/app/src/main/java/org/pizzeria/worker/Worker.java
> +    protected boolean canWork;
кажется, эта переменная должна быть volatile

2024-04-09 15:38 UTC, galinabykova commented on task_2_2_1/app/src/main/java/org/pizzeria/worker/Worker.java
> +    protected boolean canWork;
ещё похожее поведение можно было получить, используя interrupted (остановку потока с проверкой статуса), но твоё решение тоже хорошее

2024-04-09 15:38 UTC, galinabykova commented on task_2_2_1/app/src/main/java/org/pizzeria/worker/baker/Baker.java
> +                logger.log("Baking " + order.name() + " with id: " + order.id());
у тебя вот этот код дублируется много раз. Подумай, как бы от этого избавиться)

2024-04-15 13:49 UTC, vlasival commented on task_2_2_1/app/src/main/java/org/pizzeria/Pizzeria.java
> +    public void addOrder(int count) throws InterruptedException {
Добавил такие тесты в Baker, Courier Test классы

2024-04-16 08:04 UTC, galinabykova approved these changes

2024-04-16 08:04 UTC, merged