task_2_3_1
vlasival/OOP pull request #24
Opened 2024-04-30 14:59 UTC by vlasival

2024-05-02 05:03 UTC, galinabykova requested changes
хорошо, что у тебя не смешивается представление с бизнес-логикой (по крайней мере я не заметила) ). Нужно добавить тестик и ещё написать мне, какой паттерн использовал. Ещё надо бы добавить fxml, чтобы ты потыкал его

2024-05-08 17:16 UTC, vlasival commented
Добавил FXML два окна: менюшка с выбором сложности игры и сама игра. Планировал ещё использовать свои текстуры и сохранение конфига игры в json, но не успел(

2024-05-08 17:47 UTC, galinabykova requested changes
Ты проделал большую работу, молодец) всё хорошо разделено, по коду замечаний нет, поправь ещё ревью дог

2024-05-08 17:47 UTC, galinabykova commented on task_2_3_1/app/src/main/java/org/snake/viewmodel/View.java
а почему view?

2024-05-09 04:11 UTC, vlasival commented on task_2_3_1/app/src/main/java/org/snake/viewmodel/View.java
А его реализуют классы GameView и MenuView, я так обобщил по названию)

2024-05-09 04:17 UTC, galinabykova approved these changes

2024-06-07 15:45 UTC, galinabykova approved these changes

2024-06-08 01:42 UTC, merged